name: storage_repository
description: Abstraction for persisting and reading data to platform specific storage. Best used with dependency injection approach.
version: 0.0.4
repository: https://github.com/salihagic/storage_repository

environment:
  sdk: ">=2.12.1 <3.0.0"
  flutter: ">=2.0.2"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
