name: storage_repository
description: Abstraction for reading and persisting data to platform specific storage.
version: 1.0.3
repository: https://github.com/salihagic/storage_repository

environment:
  sdk: ">=2.12.1 <3.0.0"
  flutter: ">=2.0.2"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.5
  flutter_secure_storage: ^4.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
